<?php
$this->headTitle()->setSeparator(' - ')
                  ->setAutoEscape(false);

$basePath = $this->basePath();
$this->headLink()->appendStylesheet($basePath . '/css/bootstrap.min.css')
                 ->appendStylesheet($basePath . '/css/style.css')
                 ->appendStylesheet($basePath . '/css/bootstrap-responsive.min.css')
                 ->appendStylesheet($basePath . '/css/ui-lightness.css');

$this->headLink(array(
            'rel'  => 'shortcut icon',
            'type' => 'image/vnd.microsoft.icon',
            'href' => $basePath . '/images/favicon.ico',
        ));

// HTML5 shim, for IE6-8 support of HTML elements
$this->headScript()
    //prepend , load in reverse
    ->prependFile($basePath . '/js/jquery.select-to-autocomplete.js', 'text/javascript')
    ->prependFile($basePath . '/js/bootstrap-dropdown.js', 'text/javascript')
    ->prependFile($basePath . '/js/bootstrap-modal.js', 'text/javascript')
    ->prependFile($basePath . '/js/bootstrap-tab.js', 'text/javascript')
    ->prependFile($basePath . '/js/jquery-ui-1.8.18.js', 'text/javascript')
    ->prependFile($basePath . '/js/jquery-1.7.2.min.js', 'text/javascript')
    ->prependFile($basePath . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE9',)
);

echo $this->doctype();
?>

<html lang="en">
  <head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('SpeckCommerce') ?>

    <?php echo $this->headMeta() ?>

    <!-- Le styles -->
    <?php echo $this->headLink() ?>

    <!-- Scripts -->
    <?php echo $this->headScript() ?>

  </head>

  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="brand" href="<?php echo $this->url('home') ?>">SpeckCommerce</a>
          <div class="nav-collapse">
            <ul class="nav">
              <li class="active"><a href="<?php echo $this->url('home') ?>">Home</a></li>
              </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">

      <?php echo $this->content; ?>

      <hr>

      <footer>
        <p>Powered by <a href="http://speckcommerce.org/">SpeckCommerce</a>.</p>
        <p>Icons provided by <a title="GLYPHICONS is a library of precisely prepared monochromatic icons and symbols, created with an emphasis on simplicity and easy orientation." href="http://www.glyphicons.com/">glyphicons.com</a></p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>
